### ISSUE TITLE
How to set certificate pass phrase?

### ISSUE THREAD

**Issue by manuks** [corneldamian/APNs#1]
I have a certificate .pem file with a pass phrase? How to use this in the Init configuration?

**Comment by manuks** [comment]
Hi Cornel
Sorry if I am writing anything stupid here.
Should we convert the pem to certificate and key files? 
Or will it work if I copy and paste the key and secret sections from the .pem file? When I tried like that I got the following error in the logger

``` javascript
Unable to start a new apple connection: EOF
```

Any help on this is highly appreciated.

Thanks & Regards
Manu

**Comment by corneldamian** [comment]
Hi Manu

Regarding the certificates with pass phrase, right now this isn't supported by this packages, but i will investigate to see how can i do this.

The error with EOF is because the connection was closed from apple side. To check if your certificates are ok you can do like this: 

`openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert myapnsappcert.pem -key myapnsappprivatekey.pem`

Let me know if this is fixing your problem.

Regards,
Cornel
